project_id = "cttirpxnbtkjqfmhyswp"

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.fetch-twitter-post]
verify_jwt = false

[functions.fetch-linkedin-post]
verify_jwt = false

[functions.fetch-instagram-post]
verify_jwt = false

[functions.fetch-youtube-comment]
verify_jwt = false

[functions.fetch-facebook-post]
verify_jwt = false
